# Generated by Django 4.2.3 on 2023-09-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='state',
            new_name='status',
        ),
    ]
