# Generated by Django 4.2.3 on 2023-08-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdocument_deleted_at_userdocument_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='deleted_at',
        ),
    ]
