# Generated by Django 4.2.3 on 2023-08-05 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_user_reference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='have_ISLR_declaration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='have_consignment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='have_health_insurance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landline_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_place', models.CharField(max_length=200, null=True)),
                ('landline_number', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('have_health_insurance', models.BooleanField(null=True)),
                ('have_ISLR_declaration', models.BooleanField(null=True)),
                ('have_consignment', models.BooleanField(null=True)),
                ('score', models.IntegerField(default=0, help_text='Credit score')),
                ('contact_user_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='users.usercontact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
