# Generated by Django 4.2.3 on 2023-08-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_birth_place_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustomer',
            new_name='CustomerUser',
        ),
    ]
