# Generated by Django 4.2.3 on 2023-08-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_usercustomer_customeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CI',
            new_name='country_user_id',
        ),
    ]
