# Generated by Django 4.2.3 on 2023-08-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_ci_user_country_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='have_ISLR_declaration',
            new_name='have_islr_declaration',
        ),
    ]
