# Generated by Django 4.2.3 on 2023-08-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_userdocument_url_userdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.FileField(upload_to='user_documents'),
        ),
    ]
