# Generated by Django 4.2.3 on 2023-08-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_user_id',
            field=models.CharField(blank=True, help_text='in Venezuela the CI, in spain DNI', max_length=10, unique=True),
        ),
    ]
