# Generated by Django 4.2.3 on 2023-08-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_country_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('natural', 'Natural'), ('juridic', 'Juridic')], default='natural', max_length=10),
        ),
    ]
