# Generated by Django 4.2.3 on 2023-10-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='web_page',
            field=models.TextField(null=True),
        ),
    ]
