# Generated by Django 4.2.3 on 2024-01-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_usercompany_web_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_income',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
