# Generated by Django 4.2.3 on 2023-07-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_address'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('user_score', models.IntegerField()),
                ('full_product_price', models.PositiveBigIntegerField()),
                ('initial_fee', models.PositiveBigIntegerField()),
                ('monthly_fee', models.PositiveBigIntegerField()),
                ('fees_number', models.IntegerField()),
                ('lease_reason', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_address', to='users.address')),
                
            ],
        ),
        migrations.CreateModel(
            name='PaymentDelay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('fee_number', models.PositiveBigIntegerField()),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_delays_leases', to='leases.lease')),
            ],
        ),
        migrations.CreateModel(
            name='LoanGrantor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address_room', models.CharField(max_length=50)),
                ('land_line_number', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_grantors_company', to='users.company')),
            ],
        ),
        migrations.AddField(
            model_name='lease',
            name='loan_grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_loan_grantors', to='leases.loangrantor'),
        ),
        migrations.AddField(
            model_name='lease',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='lease',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases_riders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserDocumentsLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_leases_leases', to='leases.lease')),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_leases_user_documents', to='users.userdocument')),
            ],
            options={
                'unique_together': {('user_document', 'lease')},
            },
        ),
    ]
