# Generated by Django 4.2.3 on 2024-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_rename_state_lease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='weekly_income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
