# Generated by Django 4.2.3 on 2023-08-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_id',
            field=models.CharField(default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
