# Generated by Django 4.2.3 on 2023-08-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='url',
        ),
    ]
